name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ] # Se lance quand vous poussez sur master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: chmod +x gradlew ; ./gradlew kotlinWasmUpgradeYarnLock; ./gradlew wasmJsBrowserDistributionAndCopyToProduction

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: composeApp/production/portfolio/ # Le dossier à isoler
          branch: gh-pages # La branche de destination